apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app # has to match .spec.template.metadata.labels
  serviceName: "flask-app"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: flask-app # has to match .spec.selector.matchLabels
    spec:
      #terminationGracePeriodSeconds: 10
      containers:
      - name: flask-app
        image: kjayacha/webqimage:latest
        ports:
        - containerPort: 3001


